"""buat table wisata

Revision ID: ec365034f935
Revises: 
Create Date: 2021-05-25 14:45:43.922060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec365034f935'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wisata',
    sa.Column('place_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('city', sa.String(length=30), nullable=False),
    sa.Column('price', sa.String(length=7), nullable=False),
    sa.Column('rating', sa.String(length=5), nullable=False),
    sa.Column('spend_time', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('place_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wisata')
    # ### end Alembic commands ###
